"use client"
import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import { getUser } from "@/services/auth";
import Image from "next/image";
import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FedeFlix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
const [user, setUser] = useState();

useEffect(() => {  
  const userResponse = getUser();
  setUser(userResponse);
}, []);

  return (
    <html lang="es">
      <body className={inter.className}>
        <div className="bg-black">
          <Image
            src="/fondoHome.png"
            alt="fondo"
            quality={100}
            priority
            className="opacity-20"
            fill
            sizes="100vw"
            style={{
              objectFit: "cover"
            }}></Image>
          <Navbar user={user || null} />
            {children}
        </div>
      </body>
    </html>
  );
};

